const PARTNERS = [
  {
    id: "p1",
    name: "NCR CorruPack Industries",
    category: "corrugated",
    categoryLabel: "Corrugated",
    location: "Gurugram, Haryana",
    description: "3-ply & 5-ply corrugated boxes, e-commerce mailers and bulk shipping cartons.",
    capabilities: ["Shipping boxes", "Printed cartons", "Custom sizes"],
    capacity: "120 MT/month",
  },
  {
    id: "p3",
    name: "PrintBox Solutions",
    category: "corrugated",
    categoryLabel: "Corrugated",
    location: "Faridabad, Haryana",
    description: "Flexo printed cartons, branded packaging and retail-ready corrugated displays.",
    capabilities: ["Flexo print", "Retail cartons", "Die-cut boxes"],
    capacity: "95 MT/month",
  },
  {
    id: "p4",
    name: "Maharashtra Pack Works",
    category: "corrugated",
    categoryLabel: "Corrugated",
    location: "Pune, Maharashtra",
    description: "Industrial transit packaging and heavy-duty corrugated for manufacturing clients.",
    capabilities: ["Heavy-duty", "Pallet boxes", "Export packing"],
    capacity: "150 MT/month",
  },
  {
    id: "p6",
    name: "Rajasthan Carton Mills",
    category: "corrugated",
    categoryLabel: "Corrugated",
    location: "Jaipur, Rajasthan",
    description: "Cost-effective corrugated supply for retail, agriculture and distribution networks.",
    capabilities: ["Agri cartons", "Retail boxes", "Bulk supply"],
    capacity: "70 MT/month",
  },
];

const CAPACITY = [
  { value: "500+", label: "Metric tonnes / month (network)" },
  { value: "25+", label: "Partner manufacturing units" },
  { value: "3–5 ply", label: "Corrugated constructions" },
  { value: "48 hrs", label: "Typical quote turnaround" },
  { value: "12", label: "States with active partners" },
  { value: "MOQ", label: "Flexible — discussed per order" },
];

const PARTNER_FILTERS = [
  { id: "all", label: "All Partners" },
  { id: "corrugated", label: "Corrugated" },
];

const EXPORT_FILTERS = [
  { id: "all", label: "All Gifts" },
  { id: "sculptures", label: "Gift Sculptures" },
  { id: "handicrafts", label: "Brass & Metal Gifts" },
  { id: "textiles", label: "Textile Gifts" },
  { id: "pottery", label: "Pottery & Décor" },
];

/** Local images — each file matches the product labelled below */
const EXPORT_IMAGES = {
  brass: "assets/export/brass.jpg", // Brass Ganesha idol
  hero: "assets/export/hero.jpg", // Brass Buddha statue
  diya: "assets/export/handicrafts.jpg", // Brass panch aarti diya
  lamp: "assets/export/decor.jpg", // Brass Lakshmi oil lamp
  elephant: "assets/export/sculptures.jpg", // Marble elephant sculpture
  kalash: "assets/export/statue2.jpg", // Copper kalash vessel
  pottery: "assets/export/pottery.jpg", // Jaipur blue pottery vase
  potterySet: "assets/export/temple.jpg", // Blue pottery gift collection
  pashmina: "assets/export/textiles.jpg", // Elephant motif pashmina
  phulkari: "assets/export/shipping.jpg", // Phulkari embroidered textile
};

const EXPORT_PRODUCTS = [
  {
    id: "e1",
    slug: "brass-ganesha-idol",
    name: "Brass Ganesha Idol",
    category: "sculptures",
    categoryLabel: "Gift Sculptures",
    image: EXPORT_IMAGES.brass,
    images: [EXPORT_IMAGES.brass, EXPORT_IMAGES.elephant],
    material: "Brass / bronze finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Gift sizes (6\" – 24\")",
    weight: "Varies by size",
    packaging: "Gift-ready foam + export carton",
    customizable: "Yes — size & finish",
    exportNote: "Popular corporate & festive gift item",
    description:
      "Handcrafted brass Ganesha idol for gifting, home puja and cultural retail. Ideal for festive hampers and international gift buyers.",
  },
  {
    id: "e2",
    slug: "brass-buddha-statue",
    name: "Brass Buddha Statue",
    category: "sculptures",
    categoryLabel: "Gift Sculptures",
    image: EXPORT_IMAGES.hero,
    images: [EXPORT_IMAGES.hero, EXPORT_IMAGES.brass],
    material: "Brass / gold-tone metal",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Varies",
    packaging: "Shock-protected gift packing",
    customizable: "Yes",
    exportNote: "Wellness & décor gift line",
    description:
      "Ornate brass Buddha statue suited to gifting, hospitality décor and wellness retail. Packed for safe export.",
  },
  {
    id: "e3",
    slug: "brass-panch-aarti-diya",
    name: "Brass Panch Aarti Diya",
    category: "handicrafts",
    categoryLabel: "Brass & Metal Gifts",
    image: EXPORT_IMAGES.diya,
    images: [EXPORT_IMAGES.diya, EXPORT_IMAGES.lamp],
    material: "Polished brass",
    origin: "India",
    moq: "50+ pieces (typical)",
    dimensions: "Standard ritual / gift size",
    weight: "Light",
    packaging: "Gift box option available",
    customizable: "Branding on packaging",
    exportNote: "Festive & wedding gift favourite",
    description:
      "Traditional five-wick brass aarti diya — a classic Indian gift for festivals, weddings and corporate hampers.",
  },
  {
    id: "e4",
    slug: "brass-lakshmi-oil-lamp",
    name: "Brass Lakshmi Oil Lamp",
    category: "handicrafts",
    categoryLabel: "Brass & Metal Gifts",
    image: EXPORT_IMAGES.lamp,
    images: [EXPORT_IMAGES.lamp, EXPORT_IMAGES.diya],
    material: "Polished brass",
    origin: "South India",
    moq: "50+ pieces (typical)",
    dimensions: "Tabletop gift lamp",
    weight: "Light to medium",
    packaging: "Gift box / export carton",
    customizable: "Yes",
    exportNote: "Housewarming & festive gift",
    description:
      "Ornate brass Kamatchi / Lakshmi oil lamp with engraved deity motif — premium giftware for home and puja use.",
  },
  {
    id: "e5",
    slug: "marble-elephant-sculpture",
    name: "Marble Elephant Sculpture",
    category: "sculptures",
    categoryLabel: "Gift Sculptures",
    image: EXPORT_IMAGES.elephant,
    images: [EXPORT_IMAGES.elephant, EXPORT_IMAGES.brass],
    material: "White marble",
    origin: "Rajasthan, India",
    moq: "On enquiry",
    dimensions: "Decorative gift sizes",
    weight: "Medium to heavy",
    packaging: "Crate with foam lining",
    customizable: "Size options",
    exportNote: "Luxury décor gift",
    description:
      "Hand-carved white marble elephant with traditional detailing — a distinctive gift and home décor export piece.",
  },
  {
    id: "e6",
    slug: "copper-kalash-vessel",
    name: "Copper Kalash Gift Vessel",
    category: "handicrafts",
    categoryLabel: "Brass & Metal Gifts",
    image: EXPORT_IMAGES.kalash,
    images: [EXPORT_IMAGES.kalash, EXPORT_IMAGES.lamp],
    material: "Copper / brass alloy",
    origin: "India",
    moq: "50+ pieces (typical)",
    dimensions: "Tabletop vessel with lid",
    weight: "Medium",
    packaging: "Gift wrap + carton",
    customizable: "Finish options",
    exportNote: "Ritual & décor gift",
    description:
      "Ornate copper kalash with carved detail — used as a ceremonial and decorative gift across Indian and global markets.",
  },
  {
    id: "e7",
    slug: "jaipur-blue-pottery-vase",
    name: "Jaipur Blue Pottery Vase",
    category: "pottery",
    categoryLabel: "Pottery & Décor",
    image: EXPORT_IMAGES.pottery,
    images: [EXPORT_IMAGES.pottery, EXPORT_IMAGES.potterySet],
    material: "Jaipur blue pottery ceramic",
    origin: "Jaipur, Rajasthan",
    moq: "48+ pieces (typical)",
    dimensions: "Flower vase (phuldaan)",
    weight: "Medium",
    packaging: "Divided carton for safe export",
    customizable: "Motif variants",
    exportNote: "Premium home gift",
    description:
      "Hand-painted Jaipur blue pottery vase (Raja-Rani design) — a classic Indian gift for homes, hotels and boutiques.",
  },
  {
    id: "e8",
    slug: "elephant-motif-pashmina",
    name: "Elephant Motif Pashmina Scarf",
    category: "textiles",
    categoryLabel: "Textile Gifts",
    image: EXPORT_IMAGES.pashmina,
    images: [EXPORT_IMAGES.pashmina, EXPORT_IMAGES.phulkari],
    material: "Pashmina / wool blend weave",
    origin: "India",
    moq: "100+ pieces (typical)",
    dimensions: "Standard scarf / shawl",
    weight: "Light",
    packaging: "Gift pouch / carton",
    customizable: "Colourways",
    exportNote: "Personal & corporate gift",
    description:
      "Woven pashmina-style scarf with colourful elephant motifs — ready-to-gift textile for fashion and souvenir buyers.",
  },
  {
    id: "e9",
    slug: "phulkari-embroidered-textile",
    name: "Phulkari Embroidered Textile",
    category: "textiles",
    categoryLabel: "Textile Gifts",
    image: EXPORT_IMAGES.phulkari,
    images: [EXPORT_IMAGES.phulkari, EXPORT_IMAGES.pashmina],
    material: "Cotton / silk with Phulkari embroidery",
    origin: "Punjab, India",
    moq: "50+ pieces (typical)",
    dimensions: "Shawl / throw sizes",
    weight: "Light",
    packaging: "Folded gift packing",
    customizable: "Colour & density",
    exportNote: "Heritage textile gift",
    description:
      "Contemporary Phulkari embroidery textile — vibrant handcrafted gift for fashion, décor and cultural retail.",
  },
  {
    id: "e10",
    slug: "blue-pottery-gift-set",
    name: "Blue Pottery Gift Collection",
    category: "pottery",
    categoryLabel: "Pottery & Décor",
    image: EXPORT_IMAGES.potterySet,
    images: [EXPORT_IMAGES.potterySet, EXPORT_IMAGES.pottery],
    material: "Jaipur blue pottery",
    origin: "Jaipur, Rajasthan",
    moq: "Assorted sets on enquiry",
    dimensions: "Vases, flasks & surahi forms",
    weight: "Medium",
    packaging: "Assorted set cartons",
    customizable: "Assortment mix",
    exportNote: "Curated gift assortment",
    description:
      "Assorted Jaipur blue pottery flasks and vases — curated gift collection for retailers and hospitality buyers.",
  },
];
