const CAPACITY = [
  { value: "500+", label: "Metric tonnes / month (network)" },
  { value: "25+", label: "Manufacturing units" },
  { value: "3–5 ply", label: "Corrugated constructions" },
  { value: "48 hrs", label: "Typical quote turnaround" },
  { value: "12", label: "States with active supply" },
  { value: "MOQ", label: "Flexible — discussed per order" },
];

/**
 * Contact form email delivery (Web3Forms — free)
 * 1. Open https://web3forms.com
 * 2. Enter info@b2binc.in and create an access key
 * 3. Paste the key below (also check Spam for the key email)
 */
const CONTACT_CONFIG = {
  email: "info@b2binc.in",
  phone: "+91 99998 40805",
  phoneHref: "tel:+919999840805",
  web3formsAccessKey: "aceba07c-a936-4bba-8ef5-31eb7b9bcfdb",
};
/** Local images — each file matches the product labelled below */
const EXPORT_IMAGES = {
  ganeshaStone: "assets/export/ganesha-stone.jpg",
  vishnuStone: "assets/export/vishnu-stone.jpg",
  shivaMarble: "assets/export/shiva-marble.jpg",
  shivaStone: "assets/export/shiva-stone.jpg",
  krishnaStone: "assets/export/krishna-stone.jpg",
  ramDarbar: "assets/export/ram-darbar.jpg",
  durgaBronze: "assets/export/durga-bronze.jpg",
  hanumanStone: "assets/export/hanuman-stone.jpg",
  ramaStone: "assets/export/rama-stone.jpg",
  ganeshaSilver: "assets/export/ganesha-silver.jpg",
  krishnaBronze: "assets/export/krishna-bronze.jpg",
  ganeshaDancing: "assets/export/ganesha-dancing.jpg",
  nataraja: "assets/export/nataraja.jpg",
};

const EXPORT_PRODUCTS = [
  {
    id: "e1",
    slug: "lord-ganesha-stone-sculpture",
    name: "Lord Ganesha Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.ganeshaStone,
    images: [EXPORT_IMAGES.ganeshaStone, EXPORT_IMAGES.ganeshaSilver],
    material: "Grey stone / granite finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Foam-lined export carton / crate",
    customizable: "Yes — size options",
    exportNote: "Temple & home décor sculpture",
    description:
      "Seated Lord Ganesha under an ornate carved arch (prabhavali), with axe, noose, modak and abhaya mudra. Mushika sits at the base. Inscribed श्री गणेशाय नमः — Vakratunda Mahakaya. Ideal for temples, homes and cultural retail export.",
  },
  {
    id: "e2",
    slug: "lord-vishnu-stone-sculpture",
    name: "Lord Vishnu Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.vishnuStone,
    images: [EXPORT_IMAGES.vishnuStone, EXPORT_IMAGES.ramaStone],
    material: "Dark grey stone",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Foam-lined export carton / crate",
    customizable: "Yes — size options",
    exportNote: "Dashavatara-arch Vishnu idol",
    description:
      "Standing Chaturbhuja Vishnu on a lotus pedestal holding chakra, shankha and gada, with abhaya mudra. Ornate Dashavatara-style arch and base mantra ॐ नमो भगवते वासुदेवाय ॥ श्री विष्णवे नमः ॥ — suited to temple and collector markets.",
  },
  {
    id: "e3",
    slug: "lord-shiva-marble-sculpture",
    name: "Lord Shiva on Nandi (Marble)",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.shivaMarble,
    images: [EXPORT_IMAGES.shivaMarble, EXPORT_IMAGES.shivaStone],
    material: "White marble",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Crate with foam lining",
    customizable: "Yes — size options",
    exportNote: "Marble Mahadev sculpture",
    description:
      "White marble Mahadev seated on reclining Nandi, holding trishula and damaru with serpent and crescent moon detail. Base inscribed ॐ नमः शिवाय ॥ हर हर महादेव ॥ — a premium marble export piece for puja and décor.",
  },
  {
    id: "e4",
    slug: "lord-shiva-stone-sculpture",
    name: "Lord Shiva on Nandi (Stone)",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.shivaStone,
    images: [EXPORT_IMAGES.shivaStone, EXPORT_IMAGES.shivaMarble],
    material: "Dark grey stone",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Crate with foam lining",
    customizable: "Yes — size options",
    exportNote: "Stone Mahadev sculpture",
    description:
      "Dark stone Shiva seated on Nandi with rudraksha mala, serpent, trishula and damaru. Strong temple carving style with base mantra ॐ नमः शिवाय ॥ हर हर महादेव ॥ — durable for indoor display and export packing.",
  },
  {
    id: "e5",
    slug: "lord-krishna-stone-sculpture",
    name: "Lord Krishna Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.krishnaStone,
    images: [EXPORT_IMAGES.krishnaStone, EXPORT_IMAGES.krishnaBronze],
    material: "Dark grey stone",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Foam-lined export carton / crate",
    customizable: "Yes — size options",
    exportNote: "Flute Krishna with prabhavali",
    description:
      "Lord Krishna in tribhanga pose playing the flute, framed by a peacock-and-cow carved arch. Peacock feather at the feet and base text श्रीमद् भगवतम् श्री कृष्णाय नमः — popular for homes, temples and gift retail abroad.",
  },
  {
    id: "e6",
    slug: "ram-darbar-stone-sculpture",
    name: "Ram Darbar Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.ramDarbar,
    images: [EXPORT_IMAGES.ramDarbar, EXPORT_IMAGES.ramaStone],
    material: "Grey stone",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium to heavy",
    packaging: "Foam-lined export carton / crate",
    customizable: "Yes — size options",
    exportNote: "Ramayana family panel",
    description:
      "Complete Ram Darbar panel — Lord Rama with Sita, Lakshmana and kneeling Hanuman under a carved arch. Base reads ॥ श्रीराम दरबारः ॥ सिया राम चन्द्राय नमः ॥ — a centrepiece sculpture for temples and cultural buyers.",
  },
  {
    id: "e7",
    slug: "goddess-durga-bronze-sculpture",
    name: "Goddess Durga Bronze Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.durgaBronze,
    images: [EXPORT_IMAGES.durgaBronze, EXPORT_IMAGES.nataraja],
    material: "Bronze / antique brass finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — finish options",
    exportNote: "Durga on lion with halo",
    description:
      "Multi-armed Goddess Durga seated on her lion vahana within a flame-edged aureole, holding traditional weapons with abhaya mudra. Antique bronze finish on a wooden base — suited to festive and collector export lines.",
  },
  {
    id: "e8",
    slug: "lord-hanuman-stone-sculpture",
    name: "Lord Hanuman Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.hanumanStone,
    images: [EXPORT_IMAGES.hanumanStone, EXPORT_IMAGES.ramaStone],
    material: "Grey stone",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Display sizes on enquiry",
    weight: "Medium",
    packaging: "Foam-lined export carton",
    customizable: "Yes — size options",
    exportNote: "Meditative Hanuman with gada",
    description:
      "Lord Hanuman in padmasana meditation with joined hands, ornate crown and gada beside the pedestal. Base inscribed ॥ श्री हनुमते नमः ॥ — calm devotion form for home altars and export catalogues.",
  },
  {
    id: "e9",
    slug: "lord-rama-stone-sculpture",
    name: "Lord Rama Stone Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.ramaStone,
    images: [EXPORT_IMAGES.ramaStone, EXPORT_IMAGES.ramDarbar],
    material: "Dark grey stone / resin finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — size options",
    exportNote: "Seated Rama with bow",
    description:
      "Seated Lord Rama on a lotus pedestal with bow, quiver over the shoulder and abhaya mudra, set on a circular wooden base. Compact display idol for retail and international B2B orders.",
  },
  {
    id: "e10",
    slug: "silver-ganesha-sculpture",
    name: "Silver Ganesha Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.ganeshaSilver,
    images: [EXPORT_IMAGES.ganeshaSilver, EXPORT_IMAGES.ganeshaStone],
    material: "Silver-tone metal finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — size & finish",
    exportNote: "Lotus-base silver Ganesha",
    description:
      "Polished silver-finish Ganesha on an ornate lotus base with wooden platform — axe, noose, modak and blessing mudra. Bright metallic look for festive retail and premium export programmes.",
  },
  {
    id: "e11",
    slug: "lord-krishna-bronze-sculpture",
    name: "Lord Krishna Bronze Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.krishnaBronze,
    images: [EXPORT_IMAGES.krishnaBronze, EXPORT_IMAGES.krishnaStone],
    material: "Bronze / antique brass finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — finish options",
    exportNote: "Flute Krishna with aureole",
    description:
      "Antique bronze Krishna playing the bansuri in tribhanga pose inside a circular flame aureole, peacock feather on the crown, on a wooden base. Classic South Indian metal form for décor and devotion markets.",
  },
  {
    id: "e12",
    slug: "dancing-ganesha-bronze-sculpture",
    name: "Dancing Ganesha Bronze Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.ganeshaDancing,
    images: [EXPORT_IMAGES.ganeshaDancing, EXPORT_IMAGES.nataraja],
    material: "Antique bronze / copper finish",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — finish options",
    exportNote: "Nataraja-style dancing Ganesha",
    description:
      "Dynamic dancing Ganesha within a circular prabhavali, with Mushika at the lotus base — axe, noose, modak and abhaya mudra. Antique copper-bronze finish suited to modern interiors and export gift lines.",
  },
  {
    id: "e13",
    slug: "nataraja-bronze-sculpture",
    name: "Nataraja Bronze Sculpture",
    category: "sculptures",
    categoryLabel: "Sculptures",
    image: EXPORT_IMAGES.nataraja,
    images: [EXPORT_IMAGES.nataraja, EXPORT_IMAGES.ganeshaDancing],
    material: "Patinated bronze / brass",
    origin: "India",
    moq: "On enquiry",
    dimensions: "Desktop to display sizes",
    weight: "Medium",
    packaging: "Shock-protected export packing",
    customizable: "Yes — finish options",
    exportNote: "Classic Ananda Tandava form",
    description:
      "Lord Shiva as Nataraja in Ananda Tandava within a ring of fire, standing on Apasmara — classic South Indian bronze iconography on a wooden base. A signature piece for museums, boutiques and cultural export buyers.",
  },
];
